set dotenv-load := true

# Env variables
DOCKER_ACCOUNT := env("DOCKER_ACCOUNT", "")

# Run local Postgres DB
@run-db:
    docker run \
        -d \
        -e POSTGRES_USER=user \
        -e POSTGRES_PASSWORD=password \
        -e POSTGRES_DB=todo_reminder \
        -p 5432:5432 \
        -v todo_reminder_local_db:/var/lib/postgresql \
        postgres

# Run backend
serve host="127.0.0.1" port="8000" *FLAGS:
    @echo "Starting FastAPI backend server..."
    uv run uvicorn app.main:app --host {{host}} --port {{port}} {{FLAGS}}

# Generate alembic revision
revision message:
    uv run alembic revision --autogenerate -m "{{message}}"

# Run alembic migrations
migrate:
    uv run alembic upgrade head

# Build Docker image
[working-directory: ".."]
build version online="true":
    #!/usr/bin/env bash
    account='{{ if online == "true" { DOCKER_ACCOUNT + "/" } else { "" } }}'
    docker build -f backend/docker/Dockerfile -t "${account}todo-reminder-backend:{{version}}" -t "${account}todo-reminder-backend:latest" backend/
    docker push "${account}todo-reminder-backend:{{version}}"
    docker push "${account}todo-reminder-backend:latest"

