"""fix recurrent_unit field name in task model

Revision ID: 483774ebcc22
Revises: c91cc7a4a32e
Create Date: 2025-12-30 15:26:02.228980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '483774ebcc22'
down_revision: Union[str, Sequence[str], None] = 'c91cc7a4a32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrence_unit', sa.Enum('DAYS', 'WEEKS', 'MONTHS', name='recurrenceunit'), nullable=True))
    op.drop_column('tasks', 'recurrent_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrent_unit', postgresql.ENUM('DAYS', 'WEEKS', 'MONTHS', name='recurrenceunit'), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'recurrence_unit')
    # ### end Alembic commands ###
