"""message=fix typo in task model, owner field

Revision ID: c91cc7a4a32e
Revises: d5bb205934b4
Create Date: 2025-12-15 22:19:45.042032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c91cc7a4a32e'
down_revision: Union[str, Sequence[str], None] = 'd5bb205934b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
