"""add task models and update user model with reference to task models

Revision ID: d5bb205934b4
Revises: e63d48e26aea
Create Date: 2025-12-15 21:57:07.968402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5bb205934b4'
down_revision: Union[str, Sequence[str], None] = 'e63d48e26aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=True),
    sa.Column('recurrent_unit', sa.Enum('DAYS', 'WEEKS', 'MONTHS', name='recurrenceunit'), nullable=True),
    sa.Column('specific_days_of_week', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('specific_days_of_month', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'OVERDUE', 'SNOOZED', name='taskstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(), nullable=True),
    sa.Column('last_completed_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_is_active'), 'tasks', ['is_active'], unique=False)
    op.create_index(op.f('ix_tasks_next_due_date'), 'tasks', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_completions_completed_at'), 'task_completions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_completions_task_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_completed_at'), table_name='task_completions')
    op.drop_table('task_completions')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_next_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_active'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
